# ===============================================================================
# 🧠 Goug's HomeLab Ansible Playbook
# -------------------------------------------------------------------------------
# 📦 Playbook Name   : Test playbook
# 🗓️ Run Schedule   : N/A
# 🔧 Description     : This is my test playground for testing tasks prior to production
#
# 🔐 Required Secure Variables (do NOT store in GitHub):
#   - NONE  
#
# ✅ These must be provided via Ansible Vault, Semaphore Variables/Secrets, or CI/CD env vars.
# ❌ Never store actual values in this file or in version control.
#
# GitHub Repo  : https://github.com/goug76/Home-Lab-Ansible
# Maintainer   : John Goughenour
# ===============================================================================

---
- name: Add Cockpit Public Key to Known Hostes
  hosts: all

  tasks:
    - name: add Cockpit ssh key
      ansible.posix.authorized_key:
        user: "{{user}}"
        key: "{{cockpit_key}}"