---
- name: Cockpit on PVE
  hosts: all
  become: true

  tasks:
    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: ppa:cockpit-project/cockpit
        state: present

    - name: Install Cockpit
      ansible.builtin.apt:
        pkg:
          - cockpit
          - cockpit-docker
        state: latest
        update_cache: true

    - name: Enable Cockpit
      ansible.builtin.systemd_service:
        name: cockpit.socket
        state: started
        enabled: true
    
    - name: Add Cockpit modules
      ansible.builtin.apt:
        deb: "{{ item.url }}"
      loop:
        - url: https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb