---
- name: Media Provisioning
  hosts: all
  become: true

  tasks:
    
    - name: Add Cockpit modules
      ansible.builtin.apt:
        deb: "{{ item.url }}"
      loop:
        - url: https://github.com/45Drives/cockpit-file-sharing/releases/download/v3.3.7/cockpit-file-sharing_3.3.7-1focal_all.deb
        - url: https://github.com/45Drives/cockpit-identities/releases/download/v0.1.12/cockpit-identities_0.1.12-1focal_all.deb
        - url: https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb