---
- name: Media Provisioning
  hosts: all
  become: true

  tasks:

    - name: Add a dummy netowrk interface (Cockpit)
      community.general.nmcli:
        type: dummy
        conn_name: fake
        ifname: fake0
        ip4: 1.2.3.4/24
        gw4: 1.2.3.1
        state: present

    - name: Reboot if required
      ansible.builtin.reboot: