---
- name: Media Provisioning
  hosts: all
  become: true

  tasks:

    - name: Create network manager file for Cockpit
      ansible.builtin.file:
        path: /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
        state: touch

    - name: Add content to the network manager file
      ansible.builtin.lineinfile:
        path: /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
        line: "{{ item.line }}"
        state: present
      loop:
        - line: '[keyfile]'
        - line: 'unmanaged-devices=none'