---
- name: Remove "No valid subscription" popup on login to webgui
#  hosts: vm
  hosts: all
  become: yes

  tasks:
    - name: turn off screen after 1 minute of inactivity
      ansible.builtin.shell:
        cmd: echo -ne "\033[9;1]" > /dev/tty1