- name: Test Windows Update Scan
  hosts: all
  gather_facts: false

  tasks:
    - name: Search for updates
      ansible.windows.win_updates:
        state: searched
      register: result

    - debug:
        var: result.found_update_count