- name: Test Windows Update Scan
  hosts: windows
  gather_facts: false

  vars:
    windows_update_categories:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      - Updates
      - DefinitionUpdates

  tasks:
    - name: Search for updates
      ansible.windows.win_updates:
        category_names: "{{ windows_update_categories }}"
        state: searched
      register: result

    - debug:
        var: result.found_update_count